In [3]:
import pandas as pd

In [5]:
data = pd.DataFrame({"Name":["cow","Dog","Parote","buffalo","cat","Dolphin"]})

In [6]:
data

      Name
0      cow
1      Dog
2   Parote
3  buffalo
4      cat
5  Dolphin

In [11]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le = LabelEncoder()
new = le.fit_transform(data["Name"])

In [25]:
data["e_Name"] = new

In [26]:
data

      Name  e_Name
0      cow       5
1      Dog       0
2   Parote       2
3  buffalo       3
4      cat       4
5  Dolphin       1

In [27]:
data1 = pd.read_csv("Loan.csv")

In [40]:
data1.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,2,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,0,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,2,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,2,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,2,Y

In [39]:
data1["Property_Area"].unique()

array([2, 0, 1])

In [30]:
la = LabelEncoder()
la.fit(data1["Property_Area"])

LabelEncoder()

In [38]:
data1["Property_Area"] = la.transform(data1["Property_Area"])